# Generated by Django 4.1.2 on 2022-10-23 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('URL_Shortener', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CountryData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=100)),
                ('population', models.IntegerField()),
            ],
            options={
                'verbose_name_plural': 'Country Population Data',
            },
        ),
        migrations.CreateModel(
            name='Details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=50)),
                ('Device', models.CharField(max_length=50)),
            ],
        ),
    ]
