# Generated by Django 4.1.2 on 2022-10-23 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('URL_Shortener', '0003_country_device_delete_countrydata_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='country',
            old_name='country',
            new_name='country_name',
        ),
        migrations.RenameField(
            model_name='device',
            old_name='device',
            new_name='device_name',
        ),
    ]
