# Generated by Django 4.1.2 on 2022-10-23 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('URL_Shortener', '0004_rename_country_country_country_name_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Details',
        ),
        migrations.AlterField(
            model_name='country',
            name='country_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='device',
            name='device_count',
            field=models.IntegerField(default=0),
        ),
    ]
