# Generated by Django 4.1.2 on 2022-10-23 17:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('URL_Shortener', '0005_delete_details_alter_country_country_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='table',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='URL_Shortener.url_table'),
        ),
        migrations.AddField(
            model_name='device',
            name='table',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='URL_Shortener.url_table'),
        ),
    ]
